[package]
name = "xbpf"
version = "0.0.1"
edition = "2024"
description = "An ergonomic and light-weight eBPF library"
license.workspace = true
authors.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true

[dependencies]
xbpf-include = { path = "../xbpf-include" }
glob = { version = "0.3.4", optional = true }
libbpf-cargo = "0.26.2"
libbpf-rs = "0.26.2"
tracing = "0.1.44"

[dev-dependencies]
tempfile = "3.27.0"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }

[build-dependencies]
xbpf-include = { path = "../xbpf-include" }
libbpf-cargo = "0.26.2"
tracing = "0.1.44"

[features]
default = ["build", "tracing"]
build = ["dep:glob"]
tracing = []
tracing-source-loc = ["xbpf-include/tracing-source-loc"]
